/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import bean.Employé;
import dao.DaoException;
import dao.DaoFactory;
import dao.EmployeDao;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Fabien
 */
public class JIFEmployé extends javax.swing.JInternalFrame {

    
   private DaoFactory factory = DaoFactory.getInstance();
 private EmployeDao daoEmp = factory.getEmployeDao();

 private TableModelEmploye myEmpModel = new TableModelEmploye(daoEmp.selectEmployes());
    
    
    public JIFEmployé() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable(myEmpModel);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JButtonSupprimer = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Eployé"));
        setVisible(true);

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JButtonSupprimer.setText("Supprimer\n");
        JButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(232, 232, 232)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonSupprimer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(JButtonSupprimer))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           JFPrincipale parent = (JFPrincipale) (this.getDesktopPane().getTopLevelAncestor());
        new JDEmpInsert(parent, "INSERTION EMPLOYE");
        myEmpModel.setMyList(daoEmp.selectEmployes());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSupprimerActionPerformed
        if(jTable1.getSelectedRow() == -1)
           JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne svp !","Avertissement",JOptionPane.ERROR_MESSAGE); 
        
        
         else {
            int rep = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer " +
                    myEmpModel.getValueAt(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()), 0) + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION)
                try {    
                    daoEmp.deleteEmploye((Integer)myEmpModel.getValueAt(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()), 6));
                }
                catch (DaoException e) {
                    JOptionPane.showMessageDialog(null,"Suppression impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
                }
        }
        // après la suppression : rafraîchir les données en relisant la BD
        myEmpModel.setMyList(daoEmp.selectEmployes()); 
        
    }//GEN-LAST:event_JButtonSupprimerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                   if (jTable1.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(this,"Sélectionnez d'abord une ligne svp !","Avertissement",JOptionPane.ERROR_MESSAGE);
        else {
            // renvoie l'objet Appareil à passer en paramètre
           Employé employe = myEmpModel.getMyList(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));
            // récupère la JFrame parente
            JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
         new JDEmpModif(parent, "MODIFICATION EMPLOYE", employe);
            
            // après la modification : rafraîchir les données en relisant la BD
            myEmpModel.setMyList(daoEmp.selectEmployes()); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
